src/scss/generic/_heading.scss
* There are new styles of headings of the style guide - designer's request 😭 ;
=> Refactor heading sizes following the new rules of design

src/scss/components/_button.scss
*Removing margin-bottom and adding uppercase to `btn`;
=> Adding uppercase and removing margin-bottom of btn

src/scss/components/_picture.scss
* Fixing linear-gradient on small devices;
=> Fix linear on 320 of page-banner

src/html/category.html, src/scss/components/_card.scss
* Using flex on card, to avoid wrong width calc
=> Using flex on card component

src/scss/tools/mixins/_grid.scss
* `max-width: 100%` on all col-* of grid
=> Adding max-width on col-* to prevent flex wrong calc

src/scss/generic/_heading.scss, src/scss/settings/_base_font.scss
* Decreasing font-weight from heading elements;
* Removing Lato Black from project - requested by our designers.
=> Fix on heading font and removing unnecessary Lato Black

src/scss/components/_media_box.scss
* Decreasing media__content font-size;
* Removing margin-bottom from `media__header` and `media__rating`.
=> Decreasing media content font size

docs/demo/gaiden-css/components/wall/demo.html, src/scss/components/_wall.scss
I created the `wall--separator` modifier
=> Created the modify wall--separator

src/scss/components/_menu.scss, src/scss/components/_wall.scss
=> Altered the z-index in menu--cover

package.json
=> Alterded the z-index in menu--cover

src/scss/components/_dialog.scss
=> Altered the translateX value to -50% in dialog

docs/demo/gaiden-css/components/dialog/demo.html, src/scss/components/_dialog.scss
=> Altered tha font-size to 14px in dialog

src/scss/components/form/_alert-message.scss
* Increasing font of alert message
=> Increasing font-size of alert message

src/scss/components/_footer.scss, src/scss/generic/_heading.scss
* Removing font-weight 300 of Gaiden. We will not use this weight anymore.
=> 400 instead 300 unused font-weight

src/scss/generic/_reset.scss
* Adding bold to strong elements ([reset.css removes all font definitions](https://github.com/shannonmoeller/reset-css/blob/master/reset.css#L23));
=> Adding bold to strong elements

docs/demo/gaiden-css/components/footer/demo.html, src/scss/components/_footer.scss
* Moving all sticky properties of `footer--sticky` from root `footer`;
* Fixing samples of footer doc
=> Removing footer sticky properties from default footer

src/scss/components/_menu.scss, src/scss/settings/_colors.scss
* Adding shadow to the menu component
=> Adding menu shadow

src/scss/components/form/_checkbox.scss
* Fixing check icon on `form__check`;
**PRINTS** 🖼
=> Using check icon on form__check

src/scss/generic/_reset.scss
* Forcing font-family inheritance on form elements
=> fixing font-family inheritance

src/scss/tools/mixins/_get-space.scss
* Added function to retrieve the available spaces.
=> function to retrieve the desired space

sass-lint.yml, src/scss/components/_brand.scss, src/scss/components/_button.scss, src/scss/components/_card.scss, src/scss/components/_dialog.scss, src/scss/components/_footer.scss, src/scss/components/_form.scss, src/scss/components/_icon.scss, src/scss/components/_list.scss, src/scss/components/_media.scss, src/scss/components/_media_box.scss, src/scss/components/_menu.scss, src/scss/components/_page-banner.scss, src/scss/components/_pagination.scss, src/scss/components/_picture.scss, src/scss/components/_price-tag.scss, src/scss/components/_price-variation.scss, src/scss/components/_rating.scss, src/scss/components/_thumbnail.scss, src/scss/components/_wall.scss, src/scss/components/_widget.scss, src/scss/components/form/_checkbox.scss, src/scss/components/form/_radio.scss, src/scss/components/form/_steps.scss, src/scss/generic/_body.scss, src/scss/generic/_heading.scss, src/scss/tools/mixins/_clearfix.scss, src/scss/tools/mixins/_flex.scss, src/scss/tools/mixins/_generate_button_sizes.scss, src/scss/tools/mixins/_grid.scss
* This PR fix all warnings on Sass compilation. Any warnings was ignored by us, so, this PR fix this 😄 
* Applying alphabetic sort on properties, like the team internally decided;
=> Fixing lint and warnings

src/scss/settings/_spaces.scss
* Fixes the documentation of spacer classes
=> fixed spaces documentation typos

bin/build/dev/css.js
* Fixing sass-lint config file path described here https://github.com/getninjas/gaiden/issues/120
=> fixed config path

docs/demo/gaiden-css/components/wall/demo.html, src/scss/components/_wall.scss
* We need a `condensed` modifier to minor walls
=> Adding condensed modifier to wall

src/scss/settings/_buttons.scss
* Just fixing docs from button component (adding missing options);
=> Fixing documentation on button

src/scss/generic/_body.scss
* Just fixing `background-color` to wall color
=> Adding color wall to body

src/scss/components/form/_checkbox.scss, src/scss/components/form/_radio.scss
* Adding cursor pointer to checkbox and radio
=> Adding cursor pointer to checkbox and radio

docs/demo/gaiden-css/components/card/action.html, docs/demo/gaiden-css/components/card/centered.html, docs/demo/gaiden-css/components/card/custom.html, docs/demo/gaiden-css/components/card/demo.html, docs/demo/gaiden-css/components/card/grid.html, docs/demo/gaiden-css/components/media_box/fluid-action/demo.html, src/scss/components/_card.scss, src/scss/components/_media_box.scss, src/scss/components/_picture.scss
* Moves `media-box--action` to `card--action` (removing padding of `media-box__content` and `media-box__body`. There is not necesary to this component;
* `btn--full-card` belongs to `card` component, not `media-box`.
=> Moves all media-box--action props to card--action

src/scss/settings/_base_font.scss, src/scss/settings/_spaces.scss
* Add `get-space()` helper documentation.
* Add negative number with `get-space()` helper.
* Add `get-weight()` documentation
=> Add spaces and weight helpers documentation

package-lock.json, src/scss/components/_button.scss
* All our buttons will have font-weight: 900 (`get-weight(bolder)`);
**After**
**Before**
=> New button weight

docs/demo/gaiden-css/components/card/review.html, src/scss/components/_card-review.scss, src/scss/components/_card.scss, src/scss/gaiden.scss
* Create `.card-review` class component
* Update Card's documentation with Card Review component
=> Create review card

src/scss/generic/_heading.scss
Change the container subtitle font-size (`.container-title small`).
* Mobile font-size: 16px to 14px
* Desktop font-size: 18px to 16px
=> Change container subtitle size

src/scss/components/_card-citation.scss, src/scss/components/_card-profile.scss, src/scss/components/_card.scss
* Fix width `card-profile` and `card-citation`
=> Fix width card in IE 10.

README.md, package.json
* Add `git pull --tags origin master` to process release the new version.
* Back with command reset the commit temp.
* Change command in `postversion`.
=> Update readme and adjust commands

src/scss/settings/_base_font.scss
* Arrumei o import pra ter o protocolo pq quando o script de critical css roda no tanya ele tenta encontrar uma pasta //fonts.google...
=> Fix font import

docs/demo/gaiden-css/components/card/profile.html, src/scss/components/_card-profile.scss
- Fix profile card size
- Before:
- After:
=> Fix card size

package-lock.json, src/scss/settings/_base_font.scss
**CHANGELOG** 
* Add font-display parameter Swap on the Gaiden base_font URL.
=> Add font-display parameter

docs/demo/gaiden-css/scss/base.scss, docs/demo/gaiden-css/scss/colors.scss, docs/demo/gaiden-css/scss/gradients.scss, src/scss/default/gaiden.scss, src/scss/yellow/gaiden.scss
=> Fix file structure

src/scss/yellow/components/_button.scss, src/scss/yellow/components/_card.scss, src/scss/yellow/components/_form.scss, src/scss/yellow/components/_menu.scss, src/scss/yellow/components/_page_banner.scss, src/scss/yellow/components/_thumbnail.scss
* Updating Niten styles at request page.
=> Request update

package-lock.json, package.json, src/scss/yellow/components/_header-banner.scss, src/scss/yellow/components/_list.scss
* Removing spacings that should not exist.
=> Remove extra spacings

package-lock.json, package.json, src/scss/yellow/components/_menu.scss
=> Fix border

package-lock.json, package.json
* Correct mistyped on dependencies
=> Correct dependencies

.gitignore, .storybook/.babelrc, .storybook/ninjaTheme.js, README.md, babel.config.js, package-lock.json, package.json
* Create deploy docs to gh-pages:
https://getninjas.github.io/gaiden/
=> Deploy gh-pages

src/yellow/components/button/_index.scss, src/yellow/components/button/index.stories.js, src/yellow/components/caption/_index.scss, src/yellow/components/caption/index.stories.js, src/yellow/components/heading/_index.scss, src/yellow/components/heading/index.stories.js, src/yellow/components/highlight/_index.scss, src/yellow/components/highlight/index.stories.js, src/yellow/components/quote/_index.scss, src/yellow/components/quote/index.stories.js, src/yellow/components/subtitle/_index.scss, src/yellow/components/subtitle/index.stories.js, src/yellow/components/text/_index.scss, src/yellow/components/text/index.stories.js
* Added responsive font-size to components title
* Fix imports files to generated storybook docs
=> Added responsive font-size to components title

.storybook/preview-head.html, src/yellow/components/button/_index.scss, src/yellow/components/button/index.stories.js, webpack.config.js
* Refactor Buttons component
* Create news buttons: clear, ultimate and inverse
* Create docs to button component
Link to [Docs](https://getninjas.github.io/gaiden/?path=/story/components-button--all-buttons)
=> Refactor button component

src/yellow/components/button/_index.scss
* Adjust min-width button
* Created modifier `--fluid` to button to occupy 100% of the width from container.
=> Fix width button

src/yellow/components/link/_index.scss, src/yellow/components/link/index.stories.js
* Create Link Component
URL to docs with Link Component -  https://getninjas.github.io/gaiden/?path=/story/components-link--all-links
=> Create Link component

src/yellow/components/list-link/_index.scss, src/yellow/components/list-link/index.stories.js
* Created List Link Component
URL to docs: https://getninjas.github.io/gaiden/?path=/story/components-list-link--list-link
=> Created List Link Component

src/yellow/components/shape/_index.scss, src/yellow/components/shape/index.stories.js
* Crated Shape Component
URL to Docs: https://getninjas.github.io/gaiden/?path=/story/components-shape--shape
=> Created the Shape Component

src/yellow/components/topbar/_index.scss, src/yellow/components/topbar/index.stories.js
* Create a container topbar in component
* Fix vertical align buttons in topbar
=> Adjustment topbar

src/yellow/components/topbar/_menu-icon.scss
=> Fix position menu icon

package.json
* add the current release version
=> bump version up to 22.1.0

src/yellow/gaiden.scss
* Just remove a comment of an important file.
=> Remove comments

package-lock.json, package.json
=> Change gaiden version

src/default/components/_picture.scss
* Add new format possibility for picture component 5fa3481
=> Add new picture style

src/yellow/newcomponents/buttons/_index.scss
=> Adjust style button

src/yellow/newcomponents/buttons/_index.scss
=> Adjust style Button ( 2.0 )

src/yellow/newcomponents/buttons/_index.scss, src/yellow/newcomponents/buttons/index.stories.js
* Create new button for mobile
=> Button Mobile
