- src/scss/tools/mixins/_grid.scss
* Now, the designers want a padding on container, to prevent container paste on the both sides.
**PRINTS** 🖼
> Applying container gutter/2, refactor calcs and variable names

- src/scss/components/_picture.scss
* On Firefox, if a image is broken the alt text expands the img tag box layout. `-moz-force-broken-image-icon` disable this behaviour;
> Using -moz-force-broken-image-icon

- package.json
* Sass-lint now have a disable option (ex: `//sass-lint:disable no-protocol-url`).
> Updating sass-lint (to use disable feature)

- src/scss/components/_media_box.scss
* Media component had a bug on title elements with many content.
> Fixing flex direction on media__content element

- src/scss/components/_media_box.scss
* Fix on media__content to break-all content
> Fixing word-break on media__content

- src/scss/components/_media_box.scss
* Ops. Using break-word, instead break-all.
> break-word instead break-all on media__content

- documentjs.json
* Removing debug of documentjs. This log are obfuscating other logs, like sass-lint (reference to #48 )
> Removing debug option of documentjs

- src/scss/components/_list.scss
* Suggested by @MarcoBrunoBR , we are using `translateX` instead padding to animate list hover.
\*8px is the real movement of `list__item`. 14px was a number that counted with the flexbox calculation
> Using transform transition instead padding on list

- docs/demo/gaiden-css/components/dialog/demo.html
- src/scss/components/_dialog.scss
* Fixing flexbox issues on dialog component;
* Renaming the `dialog__user` elements;
**PRINTS** 🖼 
The height of dialog elements are equal now.
❗️  **BREAK CHANGE** ❗️ 
About the renaming of `dialog__user` elements. Now, we are calling `dialog__user` nested childrens by `dialog__user-name`, `dialog__user-location` instead `dialog__user__name`, `dialog__user__location`. This way is more BEM style than before. The concept of element of element don't exists on BEM methodology.
> Dialog fix flexbox and renaming dialog elements

- src/scss/components/_footer.scss
* Footer disclaimer was assuming a text-align left from another parent element.
> Removing inherit value from footer disclaimer

- src/scss/components/_thumbnail.scss
* Fixing inverted thumbnail__photo
* Problem description:
After a crossbrowser refactor on the thumbnail--action component, the thumbnail__photo element was affected because both inherit the same class (thumbnail__photo).
* Solution:
Moved the change from thumbnail__photo  to thumbnail--action scope
> removed inverted scale

- docs/demo/gaiden-css/generic/headings/demo.html
- docs/demo/gaiden-css/generic/headings/with-class/demo.html
- src/scss/generic/_heading.scss
* Just a minor fix to h5 heading element. The visual class equivalent is info-title, not card-title.
> Fixing visual equivalent h5 class

- docs/demo/gaiden-css/components/thumbnail/action/demo.html
* Removing unnecessary class from Thumbnail demos, causing the caption to be too big
> removing unnecessary class from demos

- src/scss/components/_card.scss
* Removing padding-bottom from card--action scope
> removing padding-bottom from incorrect scope

- src/scss/components/_media_box.scss
**CHANGELOG**  :memo:
* Issue: #112 
* Add `break-word` to `word-wrap` property on `.media-box__body`.
**Current**
**Correct**
> Add word-wrap to media-box__body

- src/scss/components/_media_box.scss
#118 **CHANGELOG** :memo:
* Adding width to the media box title to fix the display on IE10
> fixed title width IE10

- .browser-sync-docs.js
* Using `routes` options from browsersync fix some errors on dev documentation pages
> Fixing routes to static assets on docs

- src/scss/gaiden.scss
- src/scss/generic/_reset.scss
* Import of reset-css was inside of `generic / _reset.scss`. When we had to import independent files, instead `gaiden.scss`, this dependency of reset-css was implicit.
* Now, projects that are using just of some of components need to import reset-css on their environment to Gaiden works fine.
> Moving import of resetcss outside of generic folder

- docs/demo/gaiden-css/components/list/stacked/using_grid_system/demo.html
- docs/demo/gaiden-css/components/list/using_grid_system/demo.html
- src/scss/components/_list.scss
* Lists don't need a padding when `container` is on the same element that `list` are in
> When container and list are together, there is no padding

- src/scss/components/_card.scss
* A patch fix to solve an issue on `card` component with `media` class. Now, we are using the `card` as default spacing, when we talk about padding.
> When uses media-box with card, paddings needs to obey card

- src/scss/components/_footer.scss
* Without margin-bottom, the calc of footer max-height it was wrong
> Removing 0 margin-bottom from footer element

- src/scss/components/_widget.scss
* This is a propose for `widget` class, adding a `--align-top` top modifier that solve the flex problem in some cases that we want to height between elements to different.
Before:
After:
> Add widget align top modifier

- docs/demo/gaiden-css/generic/headings/demo.html
- docs/demo/gaiden-css/generic/headings/with-class/demo.html
* Adding a descriptive table with all headings sizes on mobile and desktop
> Docs update/title sizes

- docs/demo/gaiden-css/components/list/demo.html
- docs/demo/gaiden-css/components/list/links_list/demo.html
- docs/demo/gaiden-css/components/list/on_column/demo.html
- docs/demo/gaiden-css/components/list/stacked/demo.html
- docs/demo/gaiden-css/components/list/stacked/using_grid_system/demo.html
- docs/demo/gaiden-css/components/list/using_grid_system/demo.html
- docs/demo/gaiden-css/components/list/with_icons/demo.html
- docs/demo/gaiden-css/components/list/with_row_icons/demo.html
- docs/demo/gaiden-css/components/list/with_title/demo.html
- src/scss/components/_list.scss
After talking with the designer we are updating the spacing between the items in the default list, to follow the new list layout.
> Our list with hover mouse hover will leave the gaiden in an upcoming update.
* Changes spaces between list to default list.
* Add `margin-bottom` to the title list.
* The old spacings have been moved into the list modifier that contains the hover animation in order to keep the component as it currently stands and avoid breaks in the component.
> Updates List Component

- docs/demo/gaiden-css/components/card/profile.html
- src/scss/components/_card-profile.scss
**Description**
The cards may have a slight variation when the gray part of the cart exceeds the `min-height` which is now set to` 108px`.
* Set in the `card-profile` HTML markup.
* Small adjustments in CSS.
**PRINT**
> Fix markup HTML and adjustments styles.

- src/scss/components/_card-profile.scss
- src/scss/settings/_buttons.scss
- src/scss/settings/_shadows.scss
* Change the `background-color` for the highlight text in card profile.
* Change the normal size shadow.
* Change shadow in button large to normal.
**PRINTS**
Card Profile - Before
Card Profile - After
Button - Shadow - Before
Button - Shadow - After
> Adjustments card profile and shadow size

- src/scss/components/_button.scss
- src/scss/components/_form.scss
- src/scss/components/_pagination.scss
* To fix some `warnings` in projects that use gaiden and `autoprefixer` it's need to change declaration of `transition`.
* The solution was found here:
[postcss/autoprefixer](https://github.com/postcss/autoprefixer/issues/617)
**After**
```
transition-duration: .15s;
transition-property: border-color, background-color;
transition-timing-function: ease-in;
```
**Before**
```
transition: border-color .15s ease-in, background-color .15s ease-in;
```
> Fix transition property

- .eslintrc.js
- src/scss/components/_pagination.scss
**DESCRIPTION**
Like the minify of HTML we lose the spacing of the property display: inline-block that we take into account in the pagination with this leaving the items more glued.
* Add `font-size: 0` to `.pagination` (Hack).
* Increment `margin-left` to `6px`.
**PRINT**
- As it was in our gaiden
- how is it on our site, when we have HTML minification
- after the bugfix even with the mined HTML we will have the same result as we expected before
> Change de space between item pagination

- docs/demo/gaiden-css/components/list/links_list/demo.html
- src/scss/components/_list.scss
Esse PR atualiza o component List do Gaiden que é utilizado no footer das páginas. Ele coloca de volta o efeito hover que foi retirado anteriormente.
* Adiciona hover no component List quando ele possui links
* Remove margin-bottom no component List quando ele possui links
* Adiciona espaço entre colunas na documentação do component Link List (Fluid)
**PRINTS** 🖼
* Hover no component List com links
* Hover no component List sem links
> Add hover effect to List component

- package-lock.json
- package.json
- src/scss/components/_list.scss
- It fixes a use case we have that forces to click on the text to go.
:framed_picture: 
SOLUTION
- Set full width on anchor tag to expand the clickable area.
:framed_picture:
> Fix list li click size

- src/scss/default/components/_button.scss
* Re-include button generate that should have been removed from yellow theme only.
> Include button generates again

- src/scss/yellow/components/_thumbnail.scss
* Fix height box to thumbnail component
**Screenshot** 🖼 
Before
After
> Fix height box to thumbnail component

- src/yellow/components/_card-profile.scss
* Add word-wrap in content card profile
**SCREENSHOT** 🖼
> Add word-wrap in content card profile

- src/default/gaiden.scss
- src/default/settings/_base_font.scss
- src/yellow/gaiden.scss
- src/yellow/settings/_base_font.scss
We need to load the fonts from google while resolving some issues in our internal projects
* Load fonts from google instead of project
> Temporary rollback: load fonts from the project

- src/default/gaiden.scss
- src/default/settings/_base_font.scss
- src/yellow/gaiden.scss
- src/yellow/settings/_base_font.scss
This reverts commit 723f3d0d141e5d142da8cbeb886908977ef2fc7d.
* Now we're able to load the fonts into our projects using some webpack loaders like `url-loader`:
```
{
test: /\.(woff|woff2)$/,
loader: 'url-loader',
options: {
limit: false,
path: 'fonts/',
name: 'static/[name].[ext]',
},
}
```
> Revert "temporary rollback: fonts"

- src/yellow/components/_footer.scss
- src/yellow/components/footer/_index.scss
We don't need to use spacings into main container anymore.
* Remove spacings from `.footer` class
> Fix footer spacings
